services:
  whosatmyfeeder:
    container_name: whosatmyfeeder
    build: .
    volumes:
      - ./config:/config
      - ./data:/data
      - ./frontend:/app/frontend
      - ./static:/app/static
    ports:
      - 7766:7766  # Flask backend
      - 5173:5173  # Vite dev server
      - 8765:8765  # WebSocket server
    environment:
      - PYTHONPATH=/app
      - NODE_OPTIONS=--dns-result-order=ipv4first  # Makes Node.js localhost resolution consistent
