services:
  app:
    build: .
    ports:
      - "7766:7766"
    volumes:
      - ./config:/app/config
      - ./data:/data
      - ml_models:/app/models
      - ./input:/app/input
      - ./output:/app/output
      - ./services:/app/services
    environment:
      - PYTHONPATH=/app/services/shared:/app/services
    command: ["python", "services/webui/webui.py"]
    restart: unless-stopped
    depends_on:
      - init-data

  websocket:
    build: .
    ports:
      - "8765:8765"
    volumes:
      - ./data:/data
      - ./services:/app/services
    environment:
      - PYTHONPATH=/app/services/shared:/app/services
    command: ["python", "services/websocket/websocket_server.py"]
    restart: unless-stopped
    depends_on:
      - init-data

  speciesid:
    build: .
    volumes:
      - ./config:/app/config
      - ./data:/data
      - ml_models:/app/models
      - ./services:/app/services
    environment:
      - PYTHONPATH=/app/services/shared:/app/services
    command: ["python", "services/speciesid/speciesid.py"]
    restart: unless-stopped
    depends_on:
      - init-data
      - websocket

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src:delegated
      - ./frontend/public:/app/public:delegated
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - app
      - websocket

  init-data:
    image: busybox
    volumes:
      - ./data:/data
    command: mkdir -p /data

volumes:
  ml_models:
    external: true
    name: whosatmyfeeder_ml_models
  frontend_node_modules:

networks:
  default:
    name: app_network
