version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: services/webui/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    networks:
      - app_network
    ports:
      - "7766:7766"
      - "5678:5678"  # Debug port
    volumes:
      - ./services:/app/services:delegated  # Mount all services code
      - ./migrations:/app/migrations:delegated  # Mount migrations
      - ./config:/app/config:ro
      - ./data:/data
      - ./models:/app/models:ro
      - ./input:/app/input
      - ./output:/app/output
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app/services/shared:/app/services
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["python", "-m", "services.webui.webui"]

  websocket:
    build:
      context: .
      dockerfile: services/websocket/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    networks:
      - app_network
    ports:
      - "8765:8765"
      - "5679:5679"  # Debug port
    volumes:
      - ./services:/app/services:delegated  # Mount all services code
      - ./data:/data
    environment:
      - PYTHONPATH=/app/services/shared:/app/services
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["uvicorn", "services.websocket.websocket_server:app", "--host", "0.0.0.0", "--port", "8765", "--reload"]

  speciesid:
    build:
      context: .
      dockerfile: services/speciesid/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    networks:
      - app_network
    ports:
      - "8766:8766"
      - "5680:5680"  # Debug port
    volumes:
      - ./services:/app/services:delegated  # Mount all services code
      - ./config:/app/config:ro
      - ./data:/data
      - ./models:/app/models:ro
      - ./models/model.tflite:/app/model.tflite:ro
    environment:
      - PYTHONPATH=/app/services/shared:/app/services
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["python", "-m", "services.speciesid.speciesid"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network

networks:
  app_network:
    name: app_network
