frigate:
  frigate_url: "http://your.frigate.server:5000"
  mqtt_server: "mqtt.server.local"
  mqtt_auth: true
  mqtt_username: "your_mqtt_username"
  mqtt_password: "your_mqtt_password"
  main_topic: "frigate"
  camera:
    - "Camera1"
  object: "bird"

classification:
  model: "/app/model.tflite"
  threshold: 0.7  # Standard threshold for reliable species identification

webui:
  port: 7766
  host: "0.0.0.0"

weather:
  provider: "openweathermap"
  api_key: "YOUR_OPENWEATHER_API_KEY"
  location:
    lat: 00.0000000
    lon: -00.0000000
  units: "imperial"  # "imperial" for °F or "metric" for °C
  update_interval: 300
  historical_data: true

image_processing:
  local_models:
    quality_assessment:
      type: "basic"
      threshold: 0.7
    enhancement:
      type: "real-esrgan"

  remote_models:
    openai:
      api_key: "YOUR_OPENAI_API_KEY"
      model: "gpt-4-vision-preview"
      batch_size: 10
      cost_limit: 5.00  # daily limit in USD
      prompt_template: |
        Analyze this bird photo and provide scores from 0-1 for:
        1. Image Quality:
           - Clarity (focus, resolution)
           - Composition (framing, background)
        2. Bird Behavior:
           - What is the bird doing?
           - Is this behavior interesting or rare?
        3. Special Characteristics:
           - Multiple birds?
           - Unusual pose?
           - Interesting interaction?

  storage:
    enhanced_images_path: "data/enhanced_images"
    cache_path: "data/analysis_cache"
    frigate_events_path: "/data/frigate/events"

  batch_processing:
    enabled: true
    schedule: "0 2 * * *"  # Run at 2 AM daily
    max_images_per_batch: 100
    min_detection_score: 0.8
